# Generated by Django 2.2.1 on 2019-05-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_user_male.png', upload_to='profile_pics'),
        ),
    ]
