# Generated by Django 2.2.1 on 2019-05-06 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20190507_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='date_posted',
        ),
    ]
