# Generated by Django 2.2.1 on 2019-05-06 23:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
