# Generated by Django 2.2.1 on 2019-05-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20190507_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(default='default_recipe.png', upload_to=''),
        ),
    ]
