# Generated by Django 2.2.1 on 2019-05-11 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_recipe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_image',
            new_name='image',
        ),
    ]
