# Generated by Django 2.2.1 on 2019-05-11 19:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0010_auto_20190511_2119'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Evalutation',
            new_name='Evaluation',
        ),
    ]
