# Generated by Django 2.2.1 on 2019-05-13 01:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20190512_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='lookup_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=75, unique=True),
            preserve_default=False,
        ),
    ]
