# Generated by Django 2.2.1 on 2019-05-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20190511_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='default_recipe.png', upload_to='recipe_images'),
        ),
    ]
