# Generated by Django 2.2.1 on 2019-05-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_remove_ingredient_lookup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='lookup_name',
            field=models.CharField(default='ingredient_lookup_name', max_length=75, unique=True),
        ),
    ]
