# Generated by Django 2.2.1 on 2019-06-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_ingredient_lookup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
