# Generated by Django 2.2.1 on 2019-06-19 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_recipe_hidden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='hidden',
            new_name='is_hidden',
        ),
    ]
